#! /bin/bash
echo "Enter a number(>0) Else Exit Program"
while read n
do
	sum=0
	count=1
	
	if [ $n -gt 0 ]
	then
		while [ $count -le $n ]
		do
			sum=$[$sum+$count]
			let count=$count+1
		done
		echo "The sumary is $sum"
	else
		exit	
	fi
	
	echo "Enter a number(>0)"
done

