#! /bin/bash
echo "Please input a number greater Than zero Or Exit."
while read n
do
	sum=0
	count=1
	if [ $n -gt 0 ]
	then
		while [ $count -le $n ]
		do
			sum=$[$sum+$count]
			let count=$count+1
		done
		echo "The summary is $sum."
	else
		exit
	fi
	echo "Please input a number greater than zero Or Exit."
done

